"""GEO Fixer — Generate actionable fix files from audit results.

Generates:
- robots.txt (AI crawler rules)
- llms.txt (AI site description)
- JSON-LD schema (Organization, WebPage, FAQPage)
- Meta tags snippet (OG, Twitter, canonical)
- HTML snippets ready to paste
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class GeoFixes:
    """Collection of generated fix files."""
    robots_txt: Optional[str] = None
    llms_txt: Optional[str] = None
    jsonld_schema: Optional[str] = None
    meta_tags: Optional[str] = None
    html_snippet: Optional[str] = None

    def save_all(self, output_dir: str = "./geo-fixes"):
        """Save all generated fixes to files."""
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        saved = []

        if self.robots_txt:
            p = Path(output_dir) / "robots.txt"
            p.write_text(self.robots_txt, encoding="utf-8")
            saved.append(str(p))

        if self.llms_txt:
            p = Path(output_dir) / "llms.txt"
            p.write_text(self.llms_txt, encoding="utf-8")
            saved.append(str(p))

        if self.jsonld_schema:
            p = Path(output_dir) / "schema.jsonld"
            p.write_text(self.jsonld_schema, encoding="utf-8")
            saved.append(str(p))

        if self.meta_tags:
            p = Path(output_dir) / "meta-tags.html"
            p.write_text(self.meta_tags, encoding="utf-8")
            saved.append(str(p))

        if self.html_snippet:
            p = Path(output_dir) / "head-snippet.html"
            p.write_text(self.html_snippet, encoding="utf-8")
            saved.append(str(p))

        return saved


def generate_robots_txt(
    site_url: str,
    allow_all_ai: bool = True,
    custom_rules: Optional[list[str]] = None
) -> str:
    """Generate robots.txt with AI crawler rules.

    Args:
        site_url: Base URL of the site (for sitemap reference)
        allow_all_ai: If True, allow all AI crawlers. If False, block training crawlers only.
        custom_rules: Additional custom rules to append
    """
    lines = [
        "# robots.txt — Generated by Minddistill GEO Engine",
        f"# Site: {site_url}",
        "",
        "User-agent: *",
        "Allow: /",
        "",
        "# ── AI Search Crawlers (Always Allowed) ──",
        "User-agent: OAI-SearchBot",
        "Allow: /",
        "",
        "User-agent: PerplexityBot",
        "Allow: /",
        "",
        "User-agent: ClaudeBot",
        "Allow: /",
        "",
        "User-agent: Google-Extended",
        "Allow: /",
        "",
    ]

    if allow_all_ai:
        lines.extend([
            "# ── AI Training Crawlers (Allowed) ──",
            "User-agent: GPTBot",
            "Allow: /",
            "",
            "User-agent: anthropic-ai",
            "Allow: /",
            "",
        ])
    else:
        lines.extend([
            "# ── AI Training Crawlers (Blocked) ──",
            "User-agent: GPTBot",
            "Disallow: /",
            "",
            "User-agent: anthropic-ai",
            "Disallow: /",
            "",
        ])

    lines.extend([
        "# ── Standard Search Engines ──",
        "User-agent: Googlebot",
        "Allow: /",
        "",
        "User-agent: Bingbot",
        "Allow: /",
        "",
        "User-agent: Yandex",
        "Allow: /",
        "",
        f"Sitemap: {site_url.rstrip('/')}/sitemap.xml",
        "",
    ])

    if custom_rules:
        lines.extend(["# ── Custom Rules ──"] + custom_rules + [""])

    return "\n".join(lines)


def generate_llms_txt(
    site_name: str,
    site_url: str,
    description: str,
    sections: Optional[dict[str, list[str]]] = None,
    contact_url: Optional[str] = None,
    docs_url: Optional[str] = None
) -> str:
    """Generate llms.txt file for AI crawlers.

    Args:
        site_name: Name of the site/organization
        site_url: Base URL
        description: One-paragraph site description
        sections: Dict of section_name -> list of links
        contact_url: Contact page URL
        docs_url: Documentation URL
    """
    lines = [
        f"# {site_name}",
        f"",
        f"> {description}",
        f"",
        f"## Links",
        f"",
        f"- Home: {site_url}",
    ]

    if docs_url:
        lines.append(f"- Documentation: {docs_url}")
    if contact_url:
        lines.append(f"- Contact: {contact_url}")

    if sections:
        for section_name, links in sections.items():
            lines.extend([
                f"",
                f"## {section_name}",
                f"",
            ])
            for link in links:
                if link.startswith("http"):
                    lines.append(f"- {link}")
                else:
                    lines.append(f"- {site_url.rstrip('/')}/{link.lstrip('/')}")

    lines.extend([
        "",
        "---",
        f"Generated by Minddistill GEO Engine",
        f"Last updated: 2026-06-22",
    ])

    return "\n".join(lines)


def generate_jsonld_schema(
    site_name: str,
    site_url: str,
    description: str,
    logo_url: Optional[str] = None,
    social_profiles: Optional[list[str]] = None,
    page_type: str = "WebPage",
    faq_items: Optional[list[dict[str, str]]] = None,
    author_name: Optional[str] = None,
    date_published: Optional[str] = None,
    date_modified: Optional[str] = None,
) -> str:
    """Generate JSON-LD structured data.

    Args:
        site_name: Organization/site name
        site_url: Base URL
        description: Site description
        logo_url: Logo image URL
        social_profiles: List of social media profile URLs
        page_type: Schema.org type (WebPage, Article, FAQPage, etc.)
        faq_items: List of {"question": "...", "answer": "..."} for FAQPage
        author_name: Author name (for Article type)
        date_published: Publication date (ISO format)
        date_modified: Last modified date (ISO format)
    """
    schemas = []

    # Organization schema
    org = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": site_name,
        "url": site_url,
        "description": description,
    }
    if logo_url:
        org["logo"] = {
            "@type": "ImageObject",
            "url": logo_url
        }
    if social_profiles:
        org["sameAs"] = social_profiles
    schemas.append(org)

    # WebPage schema
    webpage = {
        "@context": "https://schema.org",
        "@type": page_type,
        "name": site_name,
        "url": site_url,
        "description": description,
        "isPartOf": {
            "@type": "WebSite",
            "name": site_name,
            "url": site_url
        }
    }
    if date_published:
        webpage["datePublished"] = date_published
    if date_modified:
        webpage["dateModified"] = date_modified
    if author_name:
        webpage["author"] = {
            "@type": "Person",
            "name": author_name
        }
    schemas.append(webpage)

    # FAQPage schema (if provided)
    if faq_items:
        faq = {
            "@context": "https://schema.org",
            "@type": "FAQPage",
            "mainEntity": []
        }
        for item in faq_items:
            faq["mainEntity"].append({
                "@type": "Question",
                "name": item["question"],
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": item["answer"]
                }
            })
        schemas.append(faq)

    return json.dumps(schemas, indent=2, ensure_ascii=False)


def generate_meta_tags(
    site_name: str,
    site_url: str,
    page_title: str,
    description: str,
    image_url: Optional[str] = None,
    twitter_handle: Optional[str] = None,
    locale: str = "en_US",
    canonical_url: Optional[str] = None,
) -> str:
    """Generate meta tags snippet for HTML head.

    Returns HTML snippet ready to paste into <head>.
    """
    tags = [
        f"<!-- Meta Tags — Generated by Minddistill GEO Engine -->",
        f"",
        f"<!-- Basic SEO -->",
        f'<title>{page_title}</title>',
        f'<meta name="description" content="{description}">',
        f'<link rel="canonical" href="{canonical_url or site_url}">',
        f'<meta name="viewport" content="width=device-width, initial-scale=1.0">',
        f"",
        f"<!-- Open Graph -->",
        f'<meta property="og:type" content="website">',
        f'<meta property="og:title" content="{page_title}">',
        f'<meta property="og:description" content="{description}">',
        f'<meta property="og:url" content="{site_url}">',
        f'<meta property="og:site_name" content="{site_name}">',
        f'<meta property="og:locale" content="{locale}">',
    ]

    if image_url:
        tags.extend([
            f'<meta property="og:image" content="{image_url}">',
            f'<meta property="og:image:width" content="1200">',
            f'<meta property="og:image:height" content="630">',
        ])

    tags.extend([
        f"",
        f"<!-- Twitter Card -->",
        f'<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{page_title}">',
        f'<meta name="twitter:description" content="{description}">',
    ])

    if twitter_handle:
        tags.append(f'<meta name="twitter:site" content="@{twitter_handle}">')

    return "\n".join(tags)


def generate_full_head_snippet(
    site_name: str,
    site_url: str,
    page_title: str,
    description: str,
    image_url: Optional[str] = None,
    twitter_handle: Optional[str] = None,
    faq_items: Optional[list[dict[str, str]]] = None,
) -> str:
    """Generate complete <head> snippet with all fixes combined.

    Returns HTML ready to paste into <head> section.
    """
    meta = generate_meta_tags(
        site_name=site_name,
        site_url=site_url,
        page_title=page_title,
        description=description,
        image_url=image_url,
        twitter_handle=twitter_handle,
    )

    jsonld = generate_jsonld_schema(
        site_name=site_name,
        site_url=site_url,
        description=description,
        logo_url=image_url,
        faq_items=faq_items,
    )

    snippet = f"""{meta}

<!-- JSON-LD Structured Data -->
<script type="application/ld+json">
{jsonld}
</script>
"""
    return snippet


def generate_fixes_from_audit(
    audit_result,
    site_name: str,
    site_url: str,
    description: str,
    image_url: Optional[str] = None,
    twitter_handle: Optional[str] = None,
    faq_items: Optional[list[dict[str, str]]] = None,
    allow_all_ai_crawlers: bool = True,
) -> GeoFixes:
    """Generate fixes based on audit findings.

    Only generates fixes for dimensions that scored below threshold.
    """
    fixes = GeoFixes()

    # Check each dimension and generate fixes where needed
    for dim in audit_result.dimensions:
        if dim.name == "robots.txt" and dim.score < 80:
            fixes.robots_txt = generate_robots_txt(
                site_url=site_url,
                allow_all_ai=allow_all_ai_crawlers
            )

        if dim.name == "llms.txt" and dim.score < 80:
            fixes.llms_txt = generate_llms_txt(
                site_name=site_name,
                site_url=site_url,
                description=description,
                contact_url=f"{site_url.rstrip('/')}/contact",
            )

        if dim.name == "Schema/JSON-LD" and dim.score < 80:
            fixes.jsonld_schema = generate_jsonld_schema(
                site_name=site_name,
                site_url=site_url,
                description=description,
                logo_url=image_url,
                faq_items=faq_items,
            )

        if dim.name == "Meta Tags" and dim.score < 80:
            fixes.meta_tags = generate_meta_tags(
                site_name=site_name,
                site_url=site_url,
                page_title=audit_result.page_title or site_name,
                description=description,
                image_url=image_url,
                twitter_handle=twitter_handle,
            )

    # Always generate combined head snippet if any HTML fix is needed
    if any([fixes.meta_tags, fixes.jsonld_schema]):
        fixes.html_snippet = generate_full_head_snippet(
            site_name=site_name,
            site_url=site_url,
            page_title=audit_result.page_title or site_name,
            description=description,
            image_url=image_url,
            twitter_handle=twitter_handle,
            faq_items=faq_items,
        )

    return fixes
